version: '3.8'

services:
  app:
    build: .
    container_name: audiozoom_app
    ports:
      - "5001:5001" # Expose port 5000 from the app container to the host
    environment:
      - NODE_ENV
      - JWT_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_CLIENT_CALLBACK_URL
      - STRIPE_SECRET_KEY
      - STRIPE_WEBHOOK_SECRET
      - PAYPAL_CLIENT_ID
      - PAYPAL_CLIENT_SECRET
      - CLIENT_URL
      - MONGODB_URI
      - PORT
      - EMAIL_SERVICE
      - EMAIL_USER
      - EMAIL_PASS
      - ADMIN_EMAIL
      - REACT_APP_GOOGLE_CLIENT_ID
      - REACT_APP_STRIPE_PUBLIC_KEY
      - REACT_APP_API_URL
    depends_on:
      - mongo # Ensure mongo starts before the app
    volumes:
      # Optional: Mount uploads directory if you want to persist uploads outside the container
      - ./uploads:/app/server/uploads 

  mongo:
    image: mongo:latest # Use the latest official MongoDB image
    container_name: audiozoom_mongo
    ports:
      - "27017:27017" # Optional: expose mongo port to host if needed for debugging tools
    volumes:
      - mongo-data:/data/db # Persist database data in a named volume

volumes:
  mongo-data: # Define the named volume for MongoDB data 