version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    env_file:
      - ./client/.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env

# Example database service (uncomment and configure if needed)
#  mongo:
#    image: mongo:latest
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo-data:/data/db

# volumes: # Define named volumes if used
#  mongo-data: